apiVersion: apps/v1
kind: Deployment
metadata:
  name: automarket-frontend
  labels:
    app: automarket-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: automarket-frontend
  template:
    metadata:
      labels:
        app: automarket-frontend
    spec:
      containers:
        - name: frontend
          image: automarket-frontend:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: automarket-frontend-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: automarket-frontend
