apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pv-claim
  labels:
    app: automarket-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
